jwt:
  secretKey:"sskddiqqwizxzxa"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssotron?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379


logging:
  config: classpath:log4j2.yml

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true

    path: /api-docs-ui